name       : python-opt-einsum
version    : 3.3.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/o/opt_einsum/opt_einsum-3.3.0.tar.gz : 59f6475f77bbc37dcf7cd748519c0ec60722e91e63ca114e68821c0c54a46549
homepage   : https://dgasmith.github.io/opt_einsum/
license    : MIT
component  : programming.python
summary    : Optimizing numpys einsum function
description: |
    Optimized einsum can significantly reduce the overall execution time of einsum-like expressions (e.g., np.einsum, dask.array.einsum, pytorch.einsum, tensorflow.einsum) by optimizing the expression's contraction order and dispatching many operations to canonical BLAS, cuBLAS, or other specialized routines. Optimized einsum is agnostic to the backend and can handle NumPy, Dask, PyTorch, Tensorflow, CuPy, Sparse, Theano, JAX, and Autograd arrays as well as potentially any library which conforms to a standard API. See the documentation for more information.
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
