name       : python-opt-einsum
version    : 3.1.0
release    : 1
source     :
    - https://github.com/dgasmith/opt_einsum/archive/v3.1.0.tar.gz : 19d82486b19f4e25203c42aef7ee9679f0f6c7b10d352529609bd566658c032c
license    : MIT
component  : programming.python
summary    : A tensor contraction order optimizer
description: |
    Optimized einsum can significantly reduce the overall execution time of einsum-like expressions (e.g., np.einsum, dask.array.einsum, pytorch.einsum, tensorflow.einsum) by optimizing the expression's contraction order and dispatching many operations to canonical BLAS, cuBLAS, or other specialized routines. Optimized einsum is agnostic to the backend and can handle NumPy, Dask, PyTorch, Tensorflow, CuPy, Sparse, Theano, JAX, and Autograd arrays as well as potentially any library which conforms to a standard API. See the documentation for more information.
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
